#!/sbin/openrc-run

name=$RC_SVCNAME
description="WPE Webkit"

depend() {
    need net localmount loopback nginx signageos-display-linux-server
}

start() {
    ebegin "starting signageOS WPE Webkit"
    docker start wpewebkit
    eend $? "failed to start WPE Webkit"
}

stop() {
    ebegin "stopping signageOS WPE Webkit"
    docker stop wpewebkit
    eend $? "failed to stop signageOS WPE Webkit"
}
