#!/bin/sh
# exit with 0 if application is alive, 1 if not alive and 2 if it's not supposed to be running at the moment

if [ -f /run/sos_ready ]; then

    THRESHOLD=60
    last_alive=`stat --format=%Y /run/sos_ready`
    now=`date +%s`
    diff=$(( $now - $last_alive ))

    if [ $diff -ge $THRESHOLD ]; then
        exit 1
    else
        exit 0
    fi

else
    exit 2
fi
