#!/usr/bin/env bash
# returns 1 if native debug is enabled, otherwise returns 0

if [ $(cat $SIGNAGEOS_PREFIX/etc/wpewebkit/.profile | grep "export WEBKIT_INSPECTOR_SERVER=" | wc -l) -eq 0 ]; then
	exit 0
else
	exit 1
fi
