#!/usr/bin/env bash
# disables native debug

set -e

mkdir -p $SIGNAGEOS_PREFIX/etc/wpewebkit
touch $SIGNAGEOS_PREFIX/etc/wpewebkit/.profile
sed -i '/^export WEBKIT_INSPECTOR_SERVER=/d' $SIGNAGEOS_PREFIX/etc/wpewebkit/.profile
