#!/bin/sh

set -e

. /sbin/signageos-diskutils

DATA_PARTITION_FIRST_SECTOR=3147776

create_and_initialize_data_partition() {
    echo 'create data partition'
    sync
    echo "n
    p
    $DATA_PARTITION_NUM
    $DATA_PARTITION_FIRST_SECTOR

    w
    " | fdisk "$DISK" -W always
    sync
    mkfs.ext4 -F "$DATA_PARTITION"
    echo 'data partition created and initialized'
}

delete_data_partition() {
    echo 'deleting data partition'
    sync
    echo "d
    $DATA_PARTITION_NUM
    w
    " | fdisk "$DISK" -W always
    sync
    echo 'data partition deleted'
}

is_data_partition_valid() {
    data_partition_start_sector=`get_start_sector_of_partition $DISK $DATA_PARTITION`
    test "$data_partition_start_sector" = "$DATA_PARTITION_FIRST_SECTOR"
}

prepare_data() {
    if partitition_exists "$DATA_PARTITION"; then
        delete_data_partition
        reboot
        exit 0
    else
        create_and_initialize_data_partition
    fi
}


# =========== DO IT =============

prepare_data

mount "$DATA_PARTITION" /mnt # The second partition, in ext4 format, where Alpine Linux is installing in sys mode
signageos-setupdisk -m sys -k rpi2 /mnt
mount -o remount,rw /media/mmcblk0p1 # An update in the first partition is required for the next reboot.

rm -rf /media/mmcblk0p1/boot.diskless # just in case there are some remnants of incomplete factory reset or something
mkdir -p /media/mmcblk0p1/boot.diskless
cp /media/mmcblk0p1/boot/* /media/mmcblk0p1/boot.diskless/
cd /mnt # We are in the second partition
rm boot/boot # Drop the unused symbolink link

mv -f boot/* /media/mmcblk0p1/boot/
rm -Rf boot
mkdir media/mmcblk0p1 # It's the mount point for the first partition on the next reboot

ln -s media/mmcblk0p1/boot boot

rm etc/apk/cache # we don't want cache in sys mode

echo "/dev/usbdisk /media/usb vfat noauto 0 0" > etc/fstab
echo "$BOOT_PARTITION /media/mmcblk0p1 vfat ro 0 0" >> etc/fstab
echo "$SWAP_PARTITION none swap sw 0 0" >> etc/fstab
echo "$DATA_PARTITION / ext4 rw,relatime,errors=remount-ro 0 1" >> etc/fstab

cd /media/mmcblk0p1
sed -i 's/^/root=\/dev\/mmcblk0p3 /' /media/mmcblk0p1/cmdline.txt
