#!/bin/sh

set -e

. /sbin/signageos-diskutils

SWAP_PARTITION_FIRST_SECTOR=1050624
SWAP_PARTITION_LAST_SECTOR=3147775

echo 'creating swap partition'
sync
echo "n
p
$SWAP_PARTITION_NUM
$SWAP_PARTITION_FIRST_SECTOR
$SWAP_PARTITION_LAST_SECTOR
t
$SWAP_PARTITION_NUM
82
w
" | fdisk "$DISK" -W always > /dev/null
sync
mkswap "$SWAP_PARTITION"
echo 'swap partition created and initialized'
