#!/bin/sh

set -e

VERSION_FILE=/tmp/signageos/fw_upgrade_version

upgrade_fw() {
    VERSION=`cat "$VERSION_FILE"`
    rm -rf "$VERSION_FILE"
    apk update
    apk add "signageos=$VERSION"
}

if [ -f "$VERSION_FILE" ]; then
    upgrade_fw || true
fi

reboot
