#!/bin/sh

set -e

VERSION_FILE='/tmp/signageos/app_upgrade_version'

upgrade_app() {
    VERSION=`cat "$VERSION_FILE"`
    rm -rf "$VERSION_FILE"
    apk update
    apk add "signageos-display-linux=$VERSION"
}

if [ -f "$VERSION_FILE" ]; then
    upgrade_app || true
fi

reboot
