#! /bin/bash

chown -R signageos:signageos /usr/lib/signageos
chown -R signageos:signageos /var/lib/signageos
chown -R signageos:signageos /var/log/signageos

ln -sfT /media /var/lib/signageos/fs/external
