#!/usr/bin/env bash
# get video framerate returns example: "30000/1001" that means approximetly 30fps

if [ "$1" = "" ]; then
    echo "Usage: $0 <video_file>"
    echo "  video_file - Path to the video file"
    exit 1
fi

VIDEO=$1

ffprobe -v 0 -of csv=p=0 -select_streams v:0 -show_entries stream=bit_rate "$VIDEO"
