#!/usr/bin/env bash
# get video codec

if [ "$1" = "" ]; then
    echo "Usage: $0 <video_file>"
    echo "  video_file - Path to the video file"
    exit 1
fi

VIDEO=$1

ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$VIDEO"
