#!/usr/bin/env bash
# get video duration

if [ "$1" = "" ]; then
    echo "Usage: $0 <video_file>"
    echo "  video_file - Path to the video file"
    exit 1
fi

VIDEO=$1

ffprobe -v quiet -of csv=p=0 -show_entries format=duration "$VIDEO"
