#!/usr/bin/env bash
# get video resolution

if [ "$1" = "" ]; then
    echo "Usage: $0 <video_file>"
    echo "  video_file - Path to the video file"
    exit 1
fi

VIDEO=$1

ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "$VIDEO"
